package payroll;

import java.sql.Connection;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;



public class NonAdminPortal extends javax.swing.JFrame {



    public NonAdminPortal() {
        initComponents();
    }

    public NonAdminPortal(String untxt) {
        initComponents();
        updateFirstNameFromDatabase(untxt);
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                updateCurrentDateTime();
            }
        }, 0, 1000); // 1000 milliseconds = 1 second

    }

    private void updateFirstNameFromDatabase(String username) {
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/motor_ph", "root", "dmns!!404");

            String selectQuery = "SELECT ed.First_Name FROM login l " +
                                 "JOIN employee_details ed ON l.EmployeeID = ed.EmployeeID " +
                                 "WHERE l.username = ?";
            try (PreparedStatement preparedStatement = connection.prepareStatement(selectQuery)) {
                preparedStatement.setString(1, username);

                ResultSet resultSet = preparedStatement.executeQuery();

                if (resultSet.next()) {
                    lblEmployeeName.setText(resultSet.getString("First_Name") + "!");
                } else {
                    JOptionPane.showMessageDialog(this, "Employee not found.");
                }
            }
            connection.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error retrieving employee details: " + ex.getMessage());
        }
    }
    
    private void updateCurrentDateTime() {
        // Get the current date and time in 12-hour format
        SimpleDateFormat dateFormatDate = new SimpleDateFormat("MMM dd, yyyy");
        SimpleDateFormat dateFormatTime = new SimpleDateFormat("hh:mm:ss a");

        String currentDate = dateFormatDate.format(new Date());
        String currentTime = dateFormatTime.format(new Date());

        // Update the labels
        lblCurrentDate.setText(currentDate);
        lblCurrentTime.setText(currentTime);
    }
    
    private void handleButtonClick(java.awt.event.ActionEvent evt, String panelName, JButton clickedButton) {
    // Switch to the specified panel when a button is clicked
    CardLayout cardLayout = (CardLayout) centerPanel.getLayout();
    cardLayout.show(centerPanel, panelName);

    // Set the background color of the clicked button to a different color
    clickedButton.setBackground(Color.WHITE);

    // Reset the background color of other buttons
    resetButtonColors(clickedButton);
}

private void resetButtonColors(JButton clickedButton) {
    // Reset the background color of other buttons
    JButton[] buttons = {btnEmpDash, btnEmpDetails, btnEmpTimesheet, btnPayroll};
    for (JButton button : buttons) {
        if (button != clickedButton) {
            button.setBackground(null);
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCurrentTime1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        btnEmpDash = new javax.swing.JButton();
        btnEmpDetails = new javax.swing.JButton();
        btnEmpTimesheet = new javax.swing.JButton();
        btnPayroll = new javax.swing.JButton();
        botPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        p1Dashboard = new javax.swing.JPanel();
        pnlProfile = new javax.swing.JPanel();
        photopanel = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();
        btnAttachPic = new javax.swing.JButton();
        lblGreetings = new javax.swing.JLabel();
        lblEmployeeRole = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();
        pnlAttendance = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        lblCurrentTime = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblCurrentDate = new javax.swing.JLabel();
        p2EmpDet = new javax.swing.JPanel();
        p3EmpTime = new javax.swing.JPanel();
        p4Payroll = new javax.swing.JPanel();

        lblCurrentTime1.setFont(new java.awt.Font("Bahnschrift", 0, 30)); // NOI18N
        lblCurrentTime1.setForeground(new java.awt.Color(102, 102, 102));
        lblCurrentTime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentTime1.setText("00:00");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));

        mainPanel.setForeground(new java.awt.Color(204, 204, 204));
        mainPanel.setMaximumSize(new java.awt.Dimension(1080, 720));
        mainPanel.setMinimumSize(new java.awt.Dimension(1080, 720));
        mainPanel.setPreferredSize(new java.awt.Dimension(1080, 720));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(102, 102, 102));
        topPanel.setMaximumSize(new java.awt.Dimension(1080, 110));
        topPanel.setMinimumSize(new java.awt.Dimension(1080, 110));
        topPanel.setPreferredSize(new java.awt.Dimension(1060, 110));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setBackground(new java.awt.Color(153, 0, 0));
        btnLogout.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.setAlignmentY(0.0F);
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setInheritsPopupMenu(true);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        topPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 90, 40));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("MOTORPH");
        topPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 33, 230, 70));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 50)); // NOI18N
        jLabel3.setText("MOTORPH");
        topPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 230, 70));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/motor.png"))); // NOI18N
        topPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 330, 130));

        mainPanel.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1080, 110));

        buttonPanel.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        buttonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        buttonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEmpDash.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnEmpDash.setText("Dashboard");
        btnEmpDash.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnEmpDash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpDashActionPerformed(evt);
            }
        });
        buttonPanel.add(btnEmpDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        btnEmpDetails.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnEmpDetails.setForeground(new java.awt.Color(51, 51, 51));
        btnEmpDetails.setText("Employee Details");
        btnEmpDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnEmpDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpDetailsActionPerformed(evt);
            }
        });
        buttonPanel.add(btnEmpDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 270, 50));

        btnEmpTimesheet.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnEmpTimesheet.setForeground(new java.awt.Color(51, 51, 51));
        btnEmpTimesheet.setText("Payslip");
        btnEmpTimesheet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnEmpTimesheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpTimesheetActionPerformed(evt);
            }
        });
        buttonPanel.add(btnEmpTimesheet, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 270, 50));

        btnPayroll.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnPayroll.setForeground(new java.awt.Color(51, 51, 51));
        btnPayroll.setText("Payslip");
        btnPayroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayrollActionPerformed(evt);
            }
        });
        buttonPanel.add(btnPayroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 270, 50));

        mainPanel.add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1080, 50));

        botPanel.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout botPanelLayout = new javax.swing.GroupLayout(botPanel);
        botPanel.setLayout(botPanelLayout);
        botPanelLayout.setHorizontalGroup(
            botPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        botPanelLayout.setVerticalGroup(
            botPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        mainPanel.add(botPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1080, 50));

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setLayout(new java.awt.CardLayout());

        p1Dashboard.setBackground(new java.awt.Color(153, 153, 153));

        pnlProfile.setBackground(new java.awt.Color(204, 204, 204));
        pnlProfile.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        photopanel.setBackground(new java.awt.Color(255, 255, 255));
        photopanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        img.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img.setText("Photo Here");
        img.setMaximumSize(new java.awt.Dimension(196, 196));
        img.setMinimumSize(new java.awt.Dimension(196, 196));
        img.setPreferredSize(new java.awt.Dimension(196, 196));

        photopanel.setLayer(img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout photopanelLayout = new javax.swing.GroupLayout(photopanel);
        photopanel.setLayout(photopanelLayout);
        photopanelLayout.setHorizontalGroup(
            photopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(photopanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        photopanelLayout.setVerticalGroup(
            photopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(photopanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAttachPic.setFont(new java.awt.Font("Bahnschrift", 0, 10)); // NOI18N
        btnAttachPic.setText("ATTACH PICTURE");
        btnAttachPic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAttachPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachPicActionPerformed(evt);
            }
        });

        lblGreetings.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        lblGreetings.setText("Welcome,");

        lblEmployeeRole.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        lblEmployeeRole.setText("NON-ADMIN");

        lblEmployeeName.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        lblEmployeeName.setText("Name");

        javax.swing.GroupLayout pnlProfileLayout = new javax.swing.GroupLayout(pnlProfile);
        pnlProfile.setLayout(pnlProfileLayout);
        pnlProfileLayout.setHorizontalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlProfileLayout.createSequentialGroup()
                        .addComponent(lblEmployeeRole)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAttachPic))
                    .addComponent(photopanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlProfileLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblGreetings)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmployeeName)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlProfileLayout.setVerticalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(photopanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmployeeRole)
                    .addComponent(btnAttachPic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGreetings)
                    .addComponent(lblEmployeeName))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pnlAttendance.setBackground(new java.awt.Color(204, 204, 204));
        pnlAttendance.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(240, 52));
        jPanel1.setMinimumSize(new java.awt.Dimension(240, 52));
        jPanel1.setPreferredSize(new java.awt.Dimension(240, 52));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CURRENT TIME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setMaximumSize(new java.awt.Dimension(240, 52));
        jPanel2.setMinimumSize(new java.awt.Dimension(240, 52));
        jPanel2.setPreferredSize(new java.awt.Dimension(240, 52));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CURRENT DATE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(274, 52));
        jPanel3.setMinimumSize(new java.awt.Dimension(274, 52));
        jPanel3.setPreferredSize(new java.awt.Dimension(274, 52));

        lblCurrentTime.setFont(new java.awt.Font("Bahnschrift", 0, 30)); // NOI18N
        lblCurrentTime.setForeground(new java.awt.Color(102, 102, 102));
        lblCurrentTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentTime.setText("00:00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblCurrentTime)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentTime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(274, 52));
        jPanel4.setMinimumSize(new java.awt.Dimension(274, 52));
        jPanel4.setPreferredSize(new java.awt.Dimension(274, 52));

        lblCurrentDate.setFont(new java.awt.Font("Bahnschrift", 0, 30)); // NOI18N
        lblCurrentDate.setForeground(new java.awt.Color(102, 102, 102));
        lblCurrentDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentDate.setText("MM/DD/YYYY");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(lblCurrentDate)
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentDate)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAttendanceLayout = new javax.swing.GroupLayout(pnlAttendance);
        pnlAttendance.setLayout(pnlAttendanceLayout);
        pnlAttendanceLayout.setHorizontalGroup(
            pnlAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAttendanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(pnlAttendanceLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(pnlAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(pnlAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        pnlAttendanceLayout.setVerticalGroup(
            pnlAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAttendanceLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout p1DashboardLayout = new javax.swing.GroupLayout(p1Dashboard);
        p1Dashboard.setLayout(p1DashboardLayout);
        p1DashboardLayout.setHorizontalGroup(
            p1DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        p1DashboardLayout.setVerticalGroup(
            p1DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p1DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        centerPanel.add(p1Dashboard, "card2");

        p2EmpDet.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout p2EmpDetLayout = new javax.swing.GroupLayout(p2EmpDet);
        p2EmpDet.setLayout(p2EmpDetLayout);
        p2EmpDetLayout.setHorizontalGroup(
            p2EmpDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        p2EmpDetLayout.setVerticalGroup(
            p2EmpDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        centerPanel.add(p2EmpDet, "card3");

        p3EmpTime.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout p3EmpTimeLayout = new javax.swing.GroupLayout(p3EmpTime);
        p3EmpTime.setLayout(p3EmpTimeLayout);
        p3EmpTimeLayout.setHorizontalGroup(
            p3EmpTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        p3EmpTimeLayout.setVerticalGroup(
            p3EmpTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        centerPanel.add(p3EmpTime, "card4");

        p4Payroll.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout p4PayrollLayout = new javax.swing.GroupLayout(p4Payroll);
        p4Payroll.setLayout(p4PayrollLayout);
        p4PayrollLayout.setHorizontalGroup(
            p4PayrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        p4PayrollLayout.setVerticalGroup(
            p4PayrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        centerPanel.add(p4Payroll, "card5");

        mainPanel.add(centerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1080, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    private void btnEmpDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpDashActionPerformed
        // TODO add your handling code here:
         handleButtonClick(evt, "p1Dashboard", btnEmpDash);
         p1Dashboard.setVisible(true);
         p2EmpDet.setVisible(false);
         p3EmpTime.setVisible(false);
         
    }//GEN-LAST:event_btnEmpDashActionPerformed

    private void btnAttachPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachPicActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon (new ImageIcon(filename).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
        img.setIcon(imageIcon);
        
        try{
            File image = new File (filename);
            FileInputStream fix = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            
            for(int number; (number = fix.read(buf)) != -1;){
                bos.write(buf, 0, number);
            }
            person_image = bos.toByteArray();
            
            
        }catch(IOException e){
          JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnAttachPicActionPerformed

    private void btnEmpDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpDetailsActionPerformed
        // TODO add your handling code here:
        handleButtonClick(evt, "p2EmpDet", btnEmpDetails);
         p1Dashboard.setVisible(false);
         p2EmpDet.setVisible(true);
         p3EmpTime.setVisible(false);
         p4Payroll.setVisible(false);
    }//GEN-LAST:event_btnEmpDetailsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        // Create a new instance of your login frame
        loginForm loginForm = new loginForm();
    
        // Set the login frame visible
        loginForm.setVisible(true);
    
        // Dispose the current admin portal frame
        dispose();


    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnEmpTimesheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpTimesheetActionPerformed
        // TODO add your handling code here:
        handleButtonClick(evt, "p3EmpTime", btnEmpTimesheet);
         p1Dashboard.setVisible(false);
         p2EmpDet.setVisible(false);
         p3EmpTime.setVisible(true);
         p4Payroll.setVisible(false);
    }//GEN-LAST:event_btnEmpTimesheetActionPerformed

    private void btnPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayrollActionPerformed
        // TODO add your handling code here
        handleButtonClick(evt, "p4Payroll", btnPayroll);
         p1Dashboard.setVisible(false);
         p2EmpDet.setVisible(false);
         p3EmpTime.setVisible(false);
         p4Payroll.setVisible(true);        
        
    }//GEN-LAST:event_btnPayrollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NonAdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NonAdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NonAdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NonAdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NonAdminPortal().setVisible(true);
            }
        });
    }
    
    private ImageIcon format = null;
    String filename = null;
    byte[] person_image = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botPanel;
    private javax.swing.JButton btnAttachPic;
    private javax.swing.JButton btnEmpDash;
    private javax.swing.JButton btnEmpDetails;
    private javax.swing.JButton btnEmpTimesheet;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPayroll;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCurrentDate;
    private javax.swing.JLabel lblCurrentTime;
    private javax.swing.JLabel lblCurrentTime1;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblEmployeeRole;
    private javax.swing.JLabel lblGreetings;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel p1Dashboard;
    private javax.swing.JPanel p2EmpDet;
    private javax.swing.JPanel p3EmpTime;
    private javax.swing.JPanel p4Payroll;
    private javax.swing.JDesktopPane photopanel;
    private javax.swing.JPanel pnlAttendance;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

    private String getEmployeeFirstName(String loggedInUsername) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
